### ISSUE TITLE
Force Close 

### ISSUE THREAD

**Issue by OnlyFaris** [Poko-Apps/Il2cppDumpDroidGUI#1]
Force close after pressing dump >.<

**Comment by Poko-Apps** [comment]
Can you describe the issue in more detail ! Give your device details and what kind of executable are you trying to dump ? (eg. ELF , MACH-O)

**Comment by Poko-Apps** [comment]
> Force close after pressing dump >.<

Can you describe the issue in more detail ! Give your device details and what kind of executable are you trying to dump ? (eg. ELF , MACH-O)

**Comment by OnlyFaris** [comment]
> > Force close after pressing dump >.<
> 
> Can you describe the issue in more detail ! Give your device details and what kind of executable are you trying to dump ? (eg. ELF , MACH-O)

Android 10 
Dump il2cpp

**Comment by Poko-Apps** [comment]
> Android 10 Dump il2cpp

Ok , let me confirm if it's working on any other android 10 devices ! Meanwhile please check if the application have proper storage permissions .

Edit : yes it have some problem with android 10

**Comment by Poko-Apps** [comment]
I'm temporary closing the issue ! If i able to resolved it I'll inform it here.

**Comment by Poko-Apps** [comment]
Hey @OnlyFaris it's been a while, but the issue has been fixed in v2.0.1 release!
