### ISSUE TITLE
metadata version 31 not support

### ISSUE THREAD

**Issue by NightShaul** [Poko-Apps/Il2cppDumpDroidGUI#4]
please update it

**Comment by W1llyC4ndr4Pr4TAm4** [comment]
Please make new dumper because latest version not support meta data 31.

**Comment by djalolovtk** [comment]
eror damp
![Screenshot_20240830-182717_Il2CppDumperGUI](https://github.com/user-attachments/assets/819c7694-2c9a-4a87-9103-3c0f1f72a09b)
pliz update program

**Comment by Poko-Apps** [comment]
Fixed in release v2.1.1

**Comment by djalolovtk** [comment]
![Screenshot_20240902-204440_Il2CppDumperGUI](https://github.com/user-attachments/assets/842bc5b9-f520-42a3-9d93-c4d61044a993)
pliz update program eror damp

**Comment by Poko-Apps** [comment]
djalolovtk That's probably another issue, or maybe a game that is protected. I've fixed metadata 31 not support problem so I'm closing this issue.

**Comment by FlutterGenerator** [comment]
![Screenshot_20260510-205435_Il2CppDumperGUI.jpg](https://github.com/user-attachments/assets/5ff0b265-7cdc-4b9e-9c83-3a11c8ac3017)

Plz help no working @Poko-Apps
